#!/bin/sh
#
# Preparation script for setup

# Migrate eth1 port to WAN
if [ "$(uci get network.lan.ifname || true)" = "eth1" ]; then
    uci set network.lan.ifname=''
    uci set network.wan=interface
    uci set network.wan.proto='dhcp'
    uci set network.wan.ifname='eth1'
fi

# Enable a wireless access point
uci set wireless.radio0.disabled=''
uci set wireless.radio0.country='DE'
uci set wireless.radio0.channel='auto'
uci set wireless.radio0.txpower='4'


uci set wireless.@wifi-iface[0].ssid='MNet-setup'
uci set wireless.@wifi-iface[0].encryption='psk2'
uci set wireless.@wifi-iface[0].key='MNet-setup'

# Enable traffic shaping for low pings
if [ -e "/etc/config/sqm" ]; then
    uci set sqm.eth1.enabled='1'
    uci set sqm.eth1.download='8000'
    uci set sqm.eth1.upload='8000'
fi

# Set a nice hostname
uci set system.@system[0].hostname='UniGateway'
