#!/bin/sh /etc/rc.common

START=15
STOP=95
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/wpa_supplicant -d -D wired -i eth1 -c /etc/wpa_supplicant.conf
	procd_set_param respawn
	procd_close_instance
}

