#!/bin/sh
set -e

DEFAULT_WIFI_NAME="MNet-$(tr -dc 0-9a-zA-Z < /dev/urandom  | head -c 4)"
DEFAULT_WIFI_PSK=$(tr -dc 0-9a-zA-Z < /dev/urandom  | head -c 8)
WIFI_PSK="unset"

echo
echo "+----------------------+"
echo "|Internet configuration|"
echo "+----------------------+"
read -p "Please enter your HRZ username (without the @ part): " USER_NAME
read -s -p "Please enter your HRZ password: " USER_PASS
echo
read -p "Please enter the MAC address given to the HRZ: " USER_MAC


# Setup HRZ stuff
sed -i -r \
    -e "s/(.*identity=).*/\1\"$USER_NAME@students.uni-marburg.de\"/" \
    -e "s/(.*password=).*/\1\"$USER_PASS\"/" \
    /etc/wpa_supplicant.conf


# Setup WAN: Migrate eth1 from 'lan' to 'wan'
if [ "$(uci get network.lan.ifname)" = "eth1" ]; then
    uci set network.lan.ifname=''
    uci set network.wan=interface               
    uci set network.wan.proto='dhcp'                                                                                             
    uci set network.wan.ifname='eth1'
fi

if [ "$USER_MAC" ]; then
    uci set network.wan.macaddr="$USER_MAC"
fi

uci commit

# Network
echo "Restarting network, please wait..."

# Post setup
/etc/init.d/umrnet enable
/etc/init.d/umrnet start
/etc/init.d/network restart

echo 
read -p "Waiting for network. Press enter to continue and setup WiFi"

echo
echo "+------------------+"
echo "|WiFi configuration|"
echo "+------------------+"
echo "Press Ctrl+C to not configure WiFi"
echo 
read -p "Please enter a name for the WiFi network [$DEFAULT_WIFI_NAME]: " WIFI_NAME
while [ "$WIFI_PSK" = "unset" ] || [ "$WIFI_PSK" != "$WIFI_PSK2" ]; do
    read -s -p "Please enter a password for the WiFi network [$DEFAULT_WIFI_PSK]: " WIFI_PSK
    echo
    read -s -p "Please repeat: " WIFI_PSK2
    echo
    [ "$WIFI_PSK" == "$WIFI_PSK2" ] || echo "Passwords do not match, try again."    
done

echo "Setting up WiFi. Please wait..."
[ "$WIFI_NAME" ] || WIFI_NAME="$DEFAULT_WIFI_NAME"
[ "$WIFI_PSK" ] || WIFI_PSK="$DEFAULT_WIFI_PSK"

# Setup WiFi
uci set wireless.@wifi-iface[0].ssid="$WIFI_NAME"
uci set wireless.@wifi-iface[0].encryption='psk2'
uci set wireless.radio0.country='DE'
uci set wireless.@wifi-iface[0].key="$WIFI_PSK"
uci set wireless.radio0.disabled=''

uci commit

/etc/init.d/network restart
